import { useState } from 'react';
import axios from 'axios';
import { UploadCloud, ShieldCheck, ShieldAlert, Loader, CheckCircle, XCircle, Hash, ExternalLink, FileText } from 'lucide-react';

const VerifyContract = () => {
  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [dragOver, setDragOver] = useState(false);

  const handleVerify = async () => {
    if (!file) return alert('Please select a PDF file.');
    setLoading(true);
    setResult(null);
    try {
      const formData = new FormData();
      formData.append('pdf', file);
      const res = await axios.post('http://localhost:5000/api/verify', formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      setResult(res.data);
    } catch (err) {
      alert('Verification error: ' + (err.response?.data?.error || err.message));
    } finally { setLoading(false); }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setDragOver(false);
    const dropped = e.dataTransfer.files[0];
    if (dropped?.type === 'application/pdf') setFile(dropped);
    else alert('Please drop a valid PDF file.');
  };

  const reset = () => { setFile(null); setResult(null); };

  return (
    <div className="max-w-3xl mx-auto page-enter py-12 px-4">
      {/* Header */}
      <div className="text-center mb-10">
        <div className="w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-5"
          style={{ background: 'linear-gradient(135deg, rgba(16,185,129,0.15), rgba(59,130,246,0.15))', border: '1px solid rgba(16,185,129,0.25)' }}>
          <ShieldCheck className="w-8 h-8 text-emerald-500" />
        </div>
        <h1 className="text-4xl font-bold font-display mb-3">Verify a Contract</h1>
        <p className="text-sm max-w-md mx-auto leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
          Upload any PDF previously generated by Legality. We'll compute its SHA-256 hash and compare it against our blockchain records.
        </p>
      </div>

      <div className="glass p-8 space-y-6">
        {/* Drop Zone */}
        {!result && (
          <div
            onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
            onDragLeave={() => setDragOver(false)}
            onDrop={handleDrop}
            onClick={() => !file && document.getElementById('pdfInput').click()}
            className={`relative border-2 border-dashed rounded-2xl p-10 flex flex-col items-center justify-center transition-all duration-300
              ${file ? 'cursor-default' : 'cursor-pointer'}`}
            style={{
              borderColor: dragOver ? '#6366f1' : file ? 'rgba(16,185,129,0.3)' : 'var(--border-glass)',
              background: dragOver ? 'rgba(99,102,241,0.05)' : file ? 'rgba(16,185,129,0.04)' : 'transparent',
            }}
          >
            {file ? (
              <>
                <div className="w-14 h-14 rounded-xl flex items-center justify-center mb-4"
                  style={{ background: 'rgba(16,185,129,0.1)', border: '1px solid rgba(16,185,129,0.25)' }}>
                  <FileText className="w-7 h-7 text-emerald-500" />
                </div>
                <p className="font-semibold" style={{ color: 'var(--text-heading)' }}>{file.name}</p>
                <p className="text-sm mt-1" style={{ color: 'var(--text-dim)' }}>{(file.size / 1024).toFixed(1)} KB</p>
                <button onClick={(e) => { e.stopPropagation(); reset(); }}
                  className="mt-4 text-xs underline transition-colors" style={{ color: 'var(--text-dim)' }}>
                  Choose a different file
                </button>
              </>
            ) : (
              <>
                <UploadCloud className="w-12 h-12 mb-4" style={{ color: dragOver ? '#6366f1' : 'var(--text-dim)' }} />
                <p className="font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>Drop your PDF here</p>
                <p className="text-sm" style={{ color: 'var(--text-dim)' }}>or <span className="text-indigo-500 underline cursor-pointer">click to browse</span></p>
                <p className="text-xs mt-4" style={{ color: 'var(--text-dim)' }}>Only .PDF files are accepted</p>
              </>
            )}
            <input id="pdfInput" type="file" accept="application/pdf" className="hidden"
              onChange={(e) => setFile(e.target.files[0])} />
          </div>
        )}

        {/* Verify Button */}
        {file && !result && (
          <button onClick={handleVerify} disabled={loading} className="btn-primary w-full py-4 text-base font-bold">
            {loading ? (
              <span className="flex items-center gap-3">
                <Loader className="w-5 h-5 animate-spin" />
                Hashing &amp; Verifying...
              </span>
            ) : (
              <span className="flex items-center gap-3">
                <ShieldCheck className="w-5 h-5" />
                Verify Authenticity
              </span>
            )}
          </button>
        )}

        {/* Result Panel */}
        {result && (
          <div className="space-y-5" style={{ animation: 'pageEnter 0.3s ease' }}>
            <div className="p-5 rounded-2xl flex items-start gap-4" style={{
              background: result.verified ? 'rgba(16,185,129,0.06)' : 'rgba(239,68,68,0.06)',
              border: result.verified ? '1px solid rgba(16,185,129,0.2)' : '1px solid rgba(239,68,68,0.2)'
            }}>
              {result.verified
                ? <CheckCircle className="w-8 h-8 text-emerald-500 shrink-0 mt-0.5" />
                : <XCircle className="w-8 h-8 text-red-500 shrink-0 mt-0.5" />
              }
              <div>
                <h3 className="text-lg font-bold font-display" style={{ color: result.verified ? '#059669' : '#dc2626' }}>
                  {result.verified ? '✓ Contract Verified' : '✗ Not Verified'}
                </h3>
                <p className="text-sm mt-1" style={{ color: 'var(--text-secondary)' }}>{result.message}</p>
              </div>
            </div>

            <div className="p-4 rounded-xl" style={{ background: 'var(--bg-glass-sm)', border: '1px solid var(--border-glass-sm)' }}>
              <div className="flex items-center gap-2 mb-2">
                <Hash className="w-4 h-4" style={{ color: 'var(--text-dim)' }} />
                <p className="text-xs uppercase tracking-widest font-semibold" style={{ color: 'var(--text-dim)' }}>Computed SHA-256</p>
              </div>
              <p className="font-mono text-xs break-all" style={{ color: 'var(--text-primary)' }}>{result.uploadedHash}</p>
            </div>

            {result.verified && result.contract && (
              <div className="glass p-5">
                <h4 className="font-bold font-display mb-4" style={{ color: 'var(--text-heading)' }}>Matched Contract</h4>
                <div className="grid sm:grid-cols-2 gap-3">
                  <div className="info-row"><span className="info-label">Contract ID</span><span className="info-value font-mono text-xs break-all">{result.contract.contractId.slice(0,18)}...</span></div>
                  <div className="info-row"><span className="info-label">Type</span><span className="info-value">{result.contract.templateType}</span></div>
                  <div className="info-row">
                    <span className="info-label">Status</span>
                    <span>{result.contract.status === 'Completed'
                      ? <span className="badge-completed text-xs"><CheckCircle className="w-3 h-3" /> Completed</span>
                      : <span className="badge-pending text-xs">Pending</span>
                    }</span>
                  </div>
                  <div className="info-row">
                    <span className="info-label">Document Version</span>
                    <span className="text-sm font-medium" style={{ color: result.isFinalSigned ? '#059669' : '#d97706' }}>
                      {result.isFinalSigned ? 'Final Signed PDF' : 'Draft Only'}
                    </span>
                  </div>
                </div>

                {result.contract.txHash && (
                  <div className="mt-4 pt-4" style={{ borderTop: '1px solid var(--info-row-border)' }}>
                    <p className="text-xs text-indigo-500 uppercase tracking-widest font-semibold mb-2">Blockchain TX</p>
                    <p className="font-mono text-xs break-all mb-2" style={{ color: 'var(--text-secondary)' }}>{result.contract.txHash}</p>
                    <a href={`https://sepolia.etherscan.io/tx/${result.contract.txHash}`} target="_blank" rel="noopener noreferrer"
                      className="text-xs text-indigo-500 hover:text-indigo-400 flex items-center gap-1 transition-colors">
                      Verify on Etherscan <ExternalLink className="w-3 h-3" />
                    </a>
                  </div>
                )}
              </div>
            )}

            <button onClick={reset} className="btn-secondary w-full">Verify Another Document</button>
          </div>
        )}
      </div>

      <p className="text-center text-xs mt-6" style={{ color: 'var(--text-dim)' }}>
        Verification works by computing the document's SHA-256 fingerprint and comparing it against Legality's database and blockchain records.
      </p>
    </div>
  );
};

export default VerifyContract;
